ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - before: if [[ -z "$experiment" ]]; then cd 1st-release; else cd 1st-release/$experiment; fi
    command: nvm install 13.3.0 && npm install && npm start